Acesso á internet e Tv

O meu objetivo do projeto é definir a relção da escolaridade com o acesso da internet e a renda

In [2]:

#  O meu objetivo do projeto é definir a relção da escolaridade com o acesso da internet e a renda
import pandas as pd
import matplotlib.pyplot as plt
import os

print('Esperamos trabalhar no diretório')
print(os.getcwd())
print("ok")

Esperamos trabalhar no diretório
E:\Semestre 2\Ciência dos Dados\Projetos\InsperEng-CD
ok

In [3]:
dados = pd.read_excel('../PNAD2015/PES2015.xlsx')
print("ok")

ok

In [4]:
lista = ["V8005","V06111","V061111","V061112","V061113","V061114","V061115","V061116","V06112","UF","V4750","V4745"]
Selected_data = dados.loc[:,lista]
print("ok")

ok

In [5]:
Selected_data.to_csv("Dados_selecionados.csv", index=False)
print("ok")
Selected_data

ok

,V8005,V06111,V061111,V061112,V061113,V061114,V061115,V061116,V06112,UF,V4750,V4745
0,23,1.0,NaN,2.0,1.0,2.0,2.0,2.0,1.0,11,8.000000e+02,5
1,23,1.0,NaN,1.0,1.0,2.0,2.0,2.0,1.0,11,1.150000e+03,5
2,35,1.0,NaN,1.0,1.0,2.0,2.0,2.0,1.0,11,7.930000e+02,6
3,34,1.0,NaN,1.0,1.0,2.0,2.0,2.0,1.0,11,7.930000e+02,7
4,11,1.0,NaN,1.0,2.0,2.0,2.0,2.0,1.0,11,7.930000e+02,2
5,7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11,7.930000e+02,2
6,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11,7.930000e+02,1
7,18,1.0,NaN,1.0,1.0,2.0,2.0,2.0,1.0,11,7.930000e+02,5
8,46,3.0,3.0,NaN,NaN,NaN,NaN,NaN,1.0,11,2.900000e+03,2
9,81,3.0,3.0,NaN,NaN,NaN,NaN,NaN,3.0,11,2.900000e+03,2
10,71,1.0,NaN,1.0,2.0,2.0,2.0,2.0,3.0,11,1.990000e+03,2
11,47,3.0,3.0,NaN,NaN,NaN,NaN,NaN,3.0,11,3.500000e+02,3
12,24,1.0,NaN,2.0,1.0,2.0,2.0,2.0,1.0,11,3.500000e+02,5
13,28,3.0,3.0,NaN,NaN,NaN,NaN,NaN,3.0,11,1.333000e+03,5
14,50,3.0,3.0,NaN,NaN,NaN,NaN,NaN,1.0,11,1.333000e+03,3
15,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11,1.333000e+03,1
16,34,1.0,NaN,1.0,1.0,2.0,2.0,2.0,1.0,11,8.180000e+02,5
17,35,1.0,NaN,1.0,1.0,2.0,2.0,2.0,1.0,11,8.180000e+02,5
18,16,1.0,NaN,2.0,1.0,2.0,2.0,2.0,1.0,11,8.180000e+02,3
19,11,1.0,NaN,1.0,1.0,2.0,2.0,2.0,1.0,11,8.180000e+02,2
20,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11,8.180000e+02,1
21,57,1.0,NaN,1.0,1.0,2.0,2.0,2.0,1.0,11,1.716000e+03,5
22,51,1.0,NaN,1.0,2.0,2.0,2.0,2.0,1.0,11,1.716000e+03,5
23,16,1.0,NaN,1.0,1.0,2.0,2.0,2.0,1.0,11,1.716000e+03,4
24,60,1.0,NaN,1.0,1.0,2.0,2.0,2.0,1.0,11,2.500000e+03,5
25,50,1.0,NaN,1.0,1.0,2.0,2.0,2.0,1.0,11,1.400000e+03,6
26,30,1.0,NaN,1.0,1.0,2.0,2.0,2.0,1.0,11,1.400000e+03,7
27,26,1.0,NaN,1.0,1.0,2.0,2.0,2.0,1.0,11,6.660000e+02,5
28,20,1.0,NaN,2.0,1.0,2.0,2.0,2.0,1.0,11,6.660000e+02,4
29,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11,6.660000e+02,1
...,...,...,...,...,...,...,...,...,...,...,...,...
356874,15,1.0,NaN,2.0,1.0,2.0,2.0,2.0,1.0,53,1.000000e+12,2
356875,54,3.0,3.0,NaN,NaN,NaN,NaN,NaN,1.0,53,2.810000e+02,1
356876,47,3.0,3.0,NaN,NaN,NaN,NaN,NaN,1.0,53,2.810000e+02,1
356877,24,1.0,NaN,2.0,1.0,2.0,2.0,2.0,1.0,53,2.810000e+02,5
356878,22,1.0,NaN,1.0,1.0,2.0,2.0,2.0,1.0,53,2.810000e+02,4
356879,20,1.0,NaN,1.0,1.0,2.0,2.0,2.0,1.0,53,2.810000e+02,2
356880,28,1.0,NaN,1.0,1.0,2.0,2.0,2.0,1.0,53,2.810000e+02,5
356881,30,1.0,NaN,2.0,1.0,2.0,2.0,2.0,1.0,53,7.750000e+02,2
356882,31,1.0,NaN,1.0,1.0,2.0,2.0,2.0,1.0,53,7.750000e+02,2
356883,9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,53,7.750000e+02,2
356884,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,53,7.750000e+02,1
356885,32,1.0,NaN,2.0,1.0,2.0,2.0,2.0,1.0,53,6.750000e+02,5
356886,30,1.0,NaN,2.0,1.0,2.0,2.0,2.0,1.0,53,6.750000e+02,2
356887,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,53,6.750000e+02,1
356888,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,53,6.750000e+02,1
356889,34,1.0,NaN,1.0,1.0,2.0,2.0,2.0,1.0,53,1.000000e+02,2
356890,9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,53,1.000000e+02,2
356891,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,53,1.000000e+02,1
356892,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,53,1.000000e+02,1
356893,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,53,1.000000e+02,1
356894,57,3.0,3.0,NaN,NaN,NaN,NaN,NaN,1.0,53,7.960000e+02,1
356895,36,1.0,NaN,1.0,1.0,2.0,2.0,2.0,1.0,53,7.960000e+02,7
356896,18,1.0,NaN,1.0,1.0,2.0,2.0,2.0,1.0,53,7.960000e+02,5
356897,57,3.0,3.0,NaN,NaN,NaN,NaN,NaN,1.0,53,7.500000e+02,2
356898,33,1.0,NaN,1.0,1.0,2.0,2.0,2.0,1.0,53,7.500000e+02,7
356899,38,1.0,NaN,1.0,1.0,2.0,2.0,2.0,1.0,53,2.590000e+02,2
356900,39,1.0,NaN,1.0,1.0,2.0,2.0,2.0,1.0,53,2.590000e+02,2
356901,17,1.0,NaN,1.0,1.0,2.0,2.0,2.0,1.0,53,2.590000e+02,4
356902,15,1.0,NaN,1.0,1.0,2.0,2.0,2.0,1.0,53,2.590000e+02,3
356903,7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,53,2.590000e+02,1